### PR TITLE
🐛 ✨ Modified Script to delete existing Git Repository

### LINKED ISSUE #1: `npx create-react-flask "path_to_dir"` works only when proper path is given.
```bash
npx  create-react-flask <path>
```
#### The above command does not work if the path is `.` which implies current directory. It throws an error. So modify the script inside `/bin/cli.js` to fix this error.

### PR DESCRIPTION
**Pull request by sreekeshiyer**
Modified File: `/bin/cli.js`

I've added the script to delete the `.git` file for the cloned repository. 

I've tried the command in Bash and Powershell on a Windows machine without admin-permissions and it seems to work. 

Should fix #1

### CODE REVIEW

**Comment by nkilm** [comment]
#### One suggestion - check if git is already initialized or not, if no then skip `rm` step.

#### Don't forget to squash your commits into single commit.

**Comment by sreekeshiyer** [comment]
> #### One suggestion - check if git is already initialized or not, if no then skip `rm` step.
> #### Don't forget to squash your commits into a single commit.

The `rm` command deletes the git repository for this _template_, which is linked to your remote GitHub Repository. It doesn't make sense to have that repository anyway, right? 
Even if the user doesn't have an existing git repository, it'd make sense if they initialize a new one. 

Please let me know your thoughts on this.

**Comment by nkilm** [comment]
Firstly it should delete the .git which comes with npx
- later setup a new .git if .git is not initialized by user
- if .git already there then just delete the .git which came with npx

You can obeserve this when you do `npx create-react-app`

**Comment by sreekeshiyer** [comment]
Please take a look @nkilm 

I tried squash using `rebase` but it didn't work for some reason 😓 

I tried out the script and it seemed to work. I'm looking for `.git` in the main directory, if not found, the script initializes a new repository. 

Hope this is working as you expected 👍🏻

**Comment by nkilm** [comment]
#### @sreekeshiyer Okay no problem, good work!
For squashing, checkout this [stackoverflow](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together#:~:text=2754-,Use%20git%20rebase%20%2Di%20%3Cafter%2Dthis%2Dcommit%3E%20and%20replace%20%22pick%22%20on%20the%20second%20and%20subsequent%20commits%20with%20%22squash%22%20or%20%22fixup%22%2C%20as%20described%20in%20the%20manual.,-In%20this%20example) answer. Hope this helps!

**Comment by sreekeshiyer** [comment]
Hey!
Just wanted to know if this repository is participating in the `hacktoberfest`
Curious to know because I saw the hacktoberfest label in the issue.

**Comment by nkilm** [comment]
@sreekeshiyer Nope not the repository, but I noticed that issues will be considered if `hacktoberfest`  label is added along with other labels. I've added all appropriate labels, dw😄

**Comment by sreekeshiyer** [comment]
image
It says your repository is not participating, so the PR doesn't count. Maybe you need to add the `hacktoberfest` or the `hacktoberfest-accepted` label to this PR.

Thanks!

**Comment by nkilm** [comment]
Okay cool I'll add.
#### Also one question, we don't have to do this procedure of adding `hacktoberfest-accepted` to PR's if the repository itself is participating in hacktoberfest right?

**Comment by nkilm** [comment]
Check now... @sreekeshiyer

**Comment by sreekeshiyer** [comment]
image
image
image

According to the rules, or from what I understand, you just need to do one of the two things. I guess the `hacktoberfest` topic added to the repository should be enough.

**Comment by nkilm** [comment]
#### @sreekeshiyer Done!🍻

**Pull request merged**
